user:
  id: 1
  username: zs
desc: "${user.username}'s id is ${user.id}"


server:
  port: 8080
  servlet:
    context-path: /user

spring:
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      additional-exclude: WEB-INF/**
